version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tadaima-action"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-wfamexmwhgap"
s3_prefix = "tadaima-action"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
